apiVersion: demo.io/v1
kind: RsyncSource
metadata:
  name: rsync-source
spec:
  image: ghcr.io/k8svol/rsync-daemon
  replicas: 1
  username: user
  password: pass
  volume:
    name: kubelet-pod-dir
    hostPath:
      path: /var/lib/kubelet/pods
  hostName: probot
