apiVersion: demo.io/v1
kind: RsyncSource
metadata:
  name: rsync-source
spec:
  image: ghcr.io/kvclone/rsync-daemon
  username: user
  password: pass
  volume:
    name: kubelet-pod-dir
    hostPath:
      path: /var/lib/kubelet/pods
  hostName: node-1
  nodeName: node-1
